print ("Assalamu'alaikum")
print ("")
print ("Let me introduce my self. My name Zidan Lutfi Ramadhan but you can call me Zidan. My NPM is 312110304.I was born in KEBUMEN and i am 18 years old. i am very glad if you want to invit my house in purinirwana residence sukaraya.So, don't forget to call me before with the number 025155120028")
print ("")
print ("thank you")
